### PR TITLE
fix download button

### PR DESCRIPTION
**Pull request by julbrs**
Fix the #13

### CODE REVIEW

**Comment by analuspi** [comment]
So I checked out locally and  there are some cards that appears just the name and others appears multiple cards to print... I think there is something not quite right about the array of images. I had problems with the slice parameters too (the only one that worked was (0,1), but it should be (0,3).

Ps: I did a really cool course today about MongoDB

**Comment by julbrs** [comment]
Send a screenshot of the issues ?

**Comment by analuspi** [comment]
I cannot take a clear screenshot because of the small print area
Download_issue1

Download_issue2

Download_issue3

**Comment by julbrs** [comment]
Hello I have marge conflicts with `develop`.

Let's discuss of this PR tomorrow or Wed. ?

Thanks !

**Comment by analuspi** [comment]
Are you available tomorrow 12h?

**Comment by julbrs** [comment]
> Are you available tomorrow 12h?

Yes !

**Pull request merged**
