### PR TITLE
Adapt client to use the Strapi API

### PR DESCRIPTION
**Pull request by julbrs**
Very small changes

Before merge let's take a decision over Strapi. Is it OK to use strapi as our backend, as it provide a nice admin panel for the first month of product usage ?

image

### CODE REVIEW

**Comment by analuspi** [comment]
Hello. I checked the branch in my computer but I wasn't able to see the nomenclature list. Maybe it's my internet connection. I'll try tomorrow again.

**Comment by julbrs** [comment]
> Hello. I checked the branch in my computer but I wasn't able to see the nomenclature list. Maybe it's my internet connection. I'll try tomorrow again.

Hello

The backend wasn't allowing listing nomenclatures without auth, I have fixed that just now. Strange thing : I have set that on my dev server, was hoping it will be set the same on prod but nope ! It is needed to redefine auth directly on prod. Not a good point for strapi.

image

**Comment by analuspi** [comment]
The nomenclature list works fine for me now. But I had problems in rendering view and download nomenclature... It's really slow compared to the other branches... I don't know if it's a good idea changing to Strapi (seems a nice and easy painel control but it's slowing down the rendering). Could we discuss that in the next meeting?

**Comment by julbrs** [comment]
Let's close this PR as react-admin have been choosen as the solution for admin management.

**Pull request closed without merging**
