### PR TITLE
starting implementing facebook login

### LINKED ISSUE #7: Add authentication layer
* Only auth user can download content
* Only auth user can create new content
* Only auth user can edit content

Depend on authentication implemented on the backend (see [here](https://github.com/montessori-ressources/api/issues/1))

### PR DESCRIPTION
**Pull request by julbrs**
This PR will contains the social login feature to fix #7. I suggest it will be possible to login the application using the following social system:

* Facebook
* Google

I have already worked a bit on the Facebook auth but it is not yet working. I will put some documentation about how the login is working using the backend and the social system, it is not obvious !

@analuspi FYI, and I would love if you can help me on this PR, for example by adding the google part ?

### CODE REVIEW

**Comment by analuspi** [comment]
Yes, sure. I'll start to read some documentation about it.

**Comment by julbrs** [comment]
OK this PR is ready to review. I have not done everything because auth is a wide subject but I have achieve the following:
* the ui is able to auth on the backend using facebook
* the backend is compatible with that
* some route are protected like /add so it is not possible to access the route if not logged.

I am adding a bunch of new issues related to auth,

**Comment by julbrs** [comment]
@analuspi Hello do you have reviewed this one ? You can test it with a dev fb app id but it is not easy to do as you will also need a backend with dev fb app id.

Actually if you test it it will tell you that the fb app is not letting you connect... Right ?

**Comment by julbrs** [comment]
Let's merge that !

**Pull request merged**
