### PR TITLE
resize image before upload to max 1650x1650

### PR DESCRIPTION
**Pull request by julbrs**
This is to check #2 !

Easy to do with this [package](https://www.npmjs.com/package/react-image-file-resizer)

### CODE REVIEW

**Comment by analuspi** [comment]
Thanks! I will take a look on that!

**Comment by julbrs** [comment]
🚀 🚀 😃

**Comment by analuspi** [comment]
How can I check that in my local environment? Should i go to my branch develop and do a pull request?

**Comment by julbrs** [comment]
Hello

We can speak of the git flow process next meeting, but the main steps regarding pull request:

* One developer work on a feature branch then create a PR via github to allow other developers validate / check what have been done (target=develop)
* Validate / Check can be done by reading the PR content (what is inside the commits) or checkout the associated branch locally 
* Then when all is ok, the other developer 'validate' the PR
* And any dev merge the PR (in develop so) (what you have done 1h ago)
* then yes the feature is available now in develop so you can use it
* you can also merge develop in your feature branch to have the feature in your branch. (it is a good thing to do that to avoid merge conflicts when you will finish your feature)

**Comment by analuspi** [comment]
Great! Thanks! 
I also had some other ideas like: add react-router, navigation and UI components (we could discuss in the next meetings)

**Comment by julbrs** [comment]
sure !

**Pull request merged**
