### PR TITLE
Feature/header footer

### LINKED ISSUE #10: Rework the header and the footer
Now we are using bulma let's clean up the header and the footer.

Let's use a [navbar](https://bulma.io/documentation/components/navbar/) for the header, and a [footer](https://bulma.io/documentation/layout/footer/) for the footer.

Let's inspire yourself with the actual app [here](https://alpha.montessori-ressources.net)

Thanks !

### PR DESCRIPTION
**Pull request by analuspi**
Fix #10 
I'm still struggling with Bulma classes,  but the basic is done.
I didn't find a Bulma component for thumbnail.

Do you think I would be able to work in the React part from authentication?

### CODE REVIEW

**Comment by julbrs** [comment]
Hello

Nice work I love the colors !

I am just wondering if we want to see nomenclature list on all screens (add, print...) and it seems to broke the view/edit screen.

This is because of the `<main></main>` in `App.js`. Can we remove it ? 

Thanks !

**Comment by julbrs** [comment]
> Do you think I would be able to work in the React part from authentication?

Sure but I need to show do what I have done yet on backend part. And there is still lots of unknown :D

**Review by julbrs — APPROVED** [review]
good !

**Comment by julbrs** [comment]
@analuspi i let you merge ? thanks !

**Comment by analuspi** [comment]
Ops... the right position for the man is before the switch
I've just fixed it.

**Pull request merged**
